#ifndef _ALTERA_MM_BRIDGE_0_H_
#define _ALTERA_MM_BRIDGE_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'mm_bridge_0' and devices
 * connected to the following master:
 *   m0
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'led', class 'altera_avalon_pio'
 * The macros are prefixed with 'LED_'.
 * The prefix is the slave descriptor.
 */
#define LED_COMPONENT_TYPE altera_avalon_pio
#define LED_COMPONENT_NAME led
#define LED_BASE 0x3000
#define LED_SPAN 16
#define LED_END 0x300f
#define LED_BIT_CLEARING_EDGE_REGISTER 0
#define LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_CAPTURE 0
#define LED_DATA_WIDTH 8
#define LED_DO_TEST_BENCH_WIRING 0
#define LED_DRIVEN_SIM_VALUE 0
#define LED_EDGE_TYPE NONE
#define LED_FREQ 50000000
#define LED_HAS_IN 0
#define LED_HAS_OUT 1
#define LED_HAS_TRI 0
#define LED_IRQ_TYPE NONE
#define LED_RESET_VALUE 127

/*
 * Macros for device 'btn', class 'altera_avalon_pio'
 * The macros are prefixed with 'BTN_'.
 * The prefix is the slave descriptor.
 */
#define BTN_COMPONENT_TYPE altera_avalon_pio
#define BTN_COMPONENT_NAME btn
#define BTN_BASE 0x5000
#define BTN_SPAN 16
#define BTN_END 0x500f
#define BTN_BIT_CLEARING_EDGE_REGISTER 0
#define BTN_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BTN_CAPTURE 1
#define BTN_DATA_WIDTH 2
#define BTN_DO_TEST_BENCH_WIRING 0
#define BTN_DRIVEN_SIM_VALUE 0
#define BTN_EDGE_TYPE FALLING
#define BTN_FREQ 50000000
#define BTN_HAS_IN 1
#define BTN_HAS_OUT 0
#define BTN_HAS_TRI 0
#define BTN_IRQ_TYPE NONE
#define BTN_RESET_VALUE 0


#endif /* _ALTERA_MM_BRIDGE_0_H_ */
